css/styles.css, index.html, js/leaderboard.js
1. Item 1
2. Item 2
Closes #000
=> docs(Base Leaderboard) Leaderboard Html, CSS & JS

js/script.js
1. Created a class for Obstacles.
2. Created two placeholder obstacles (for testing).
3. Set obstacle to move back and forth.
4. Created a "health" variable (for testing damage). 
5. Created function to detect player and obstacle collision on which the player's health decrements. If the player has no health left, the game "restarts" by calling the startGame function. 
Create moving placeholder obstacles to test for damage. 
Closes #6
=> feat(obstacles): add placeholder obstacles

index.html, js/script.js
Adds sprite to player
Closes #29
=> Added character sprite

js/script.js
1. Player can't double jump
2. Created platforms 
3. Player cant fall through platforms 
created platforms
Closes #28
=> feat-28-add-platforms

js/script.js
1. added background image class
2. refactored obstacles to not move with the screen
3. refactor to ensure when a player reverses they don't get points taken away
Closes #4
=> Gm 4 scrolling screen

css/styles.css, index.html
1. Meow Masters Header
2. Added Placement tab for Leaderboard
3. Changed Leaderboard Font (Still Customizing)
Closes #000
=> docs(Updated Code) Header & placement tab for LB

css/styles.css, index.html, js/script.js
1. Added count down function 
Closes #0000
=> Feat(client): Start Count_down

css/styles.css, index.html, js/script.js
1. Made functions global 
2. Fixed timer countdown and timer bug
Closes #44
=> Refactored StartGame function

js/script.js
1. fix the resume function
Closes #40
=> Fix-resume-function

css/styles.css, js/script.js
1. Made the animation start with the end of the timer.
Closes #43
=> Fix countdown to start

css/styles.css, index.html, js/leaderboard.js
1. Added Cyclic Player Input
2. Re-added Unmerged Code (from #30-fs2-header)
Closes #000
=> docs(Code Added & Re-added Unmerged Code)

index.html, js/script.js
1. Add modal class 
2. Create a new instance for end score modal
3. Create a function that prompts modal if time runs out or if the player reaches the end of the level (which is currently set to a temporary scroll position)
4. Calculates and displays final score
Displays player's final score on a modal when game is over
Closes #37
=> End Score Modal 

js/script.js
1.  Added promises ensure proper display of the start word 
Closes #000
=> Countdown to Start Improvement

js/script.js
1. Item 1
2. Item 2
Closes #000
=> (testing-branch)

js/script.js
1.  The pies disappears
Closes #000
=> Feat(client) Disappearing pies

js/script.js
1. improved the score
Closes #000
=> score-improvement

css/styles.css
1. Import Butcherman font to CSS 
2. Applied Butcherman font-family to all 
Change font family to fit spooky theme
Closes #77
=> style(font): applied Butcherman font to all

css/styles.css, index.html, js/script.js
1. Removed width and height from canvas in html
2. Set fixed width and height for canvas in JS
3. Create getScore() function that sets score equal to scrollPosition
Score stays consistent regardless of screen size. 
Closes #59
=> Isabella tannady cu 3pxb30v

css/styles.css, index.html, js/script.js
1. Added End Messages to pie class
2. Added final pie
3. Added you win modal
Closes #000
=> Feat(Client): Added End Messages

js/script.js
1. Shifted the Final pie forward to 8100
Closes #000
=> Fix-Final Pie Position

js/script.js
1. Fixed Canvas size/resolution issue
=> Fix canvas size

index.html
1. Removed score from the start page 
Closes #000
=> Fix(Client):Title Menu Score

js/script.js
1. Lowered platforms 
2. added more platforms
Platforms moved off screen when sizing issue was fixed
Closes #96
=> feat-96-platforms

css/styles.css, index.html, js/script.js
_
1.create JS functionality for the score and timer to be display none 
2. create  CSS for Score and Timer
#110 
Closes #000
=> feat(Score and Timer):create to be displayed over the canvas

css/styles.css, index.html
1. Set canvas-container class to position relative
2. Set countdown and currentScore class to position absolute, relative to container
3. Changed text color 
Moved score and timer to show in canvas and changed text color for more contrast. 
Closes #103
=> fix: score and timer bg

js/script.js
1. Paws Menu display after start
Closes #000
=> Fix(Client)Pause and Resume after start

js/script.js
1. Jumping bug fixed
Closes #000
=> fix: double-jump-bug

css/styles.css
1. Fixed leaderboard Overlay
2. Removed the black background
_Links to blog posts, patterns, libraries or add-ons used to solve this problem_
Closes #000
=> updated Leaderboard overlay

css/styles.css, index.html
1. Fix responsiveness for timer and score. 
Fix timer so it's centered. 
Closes #121
=> fix: time and score responsiveness

css/styles.css, js/script.js
1. reduced the size of the submit button and made it responsive 
Closes #000
=> Fix: time up responsiveness

css/styles.css, index.html, js/leaderboard.js
1. Added Function to Click Outside of Game to close the Leaderboard Container 
2. Added Span Class in Title and Styled w/ CSS
Closes #000
=> feat(Leaderboard Closes) click outside cont.

js/script.js
1. create cat sounds
- when the player gets a pie , when the player collides with an obstacle and when the player win/time out
Closes #117
=> feat(cat-sounds):added the 3 cat sounds

css/styles.css, index.html
1. Changed image file for menu buttons to match Figma file
2. Change font color
Closes #127
=> style: update menu buttons style

js/script.js
1. Add pies on a few platforms
Pies were originally all on the ground. Scattered a few pies on platforms. 15 pies total. 
Closes #131
=> feat: pies on platforms

js/script.js
1. When on leaderboard the pause menu doesn't show.
Closes #134
=> Paws Menu Over Leaderboard

css/styles.css, index.html, js/script.js
1. Added cancel button for the time up modal.
2. Item 2
The quit button was initially removed
Closes #120
=> Quit button for time up modal

js/script.js
1. Stops the background scroll on the last frame
Doesnt allow whitespace to show in the game screen
Closes #104
=> Last background doesnt move

css/styles.css, index.html
1. Changed canvas container size to 100vw
2. Added media query for xl screens so canvas container stays within screen
3. Changed body background color to black
Closes #138
=> style: resized canvas container to full width

css/styles.css, index.html, js/script.js
1. Added cancel to the side of the leaderboard using the quit function.
Closes #139
=> Added Cancel  Button to the side of the Leader Board

js/script.js
1. Adjusted the player collision detection
The player no longer floats in air off platform
Closes #143
=> Adjusted collision on player for platforms

css/styles.css, index.html
1. Adjusted menu button positioning
2. Changed font size to vw/vh 
To make menu buttons responsive based on screen size
Closes #147
=> fix: menu button responsiveness

js/script.js
1. properly disappear the pie and 
2. Adjusting the cat-meow sound
Closes #136
=> feat(pie):creat the pie undefined

css/styles.css, index.html
1. Updated leaderboard container positioning for responsiveness
2. Added media query for large screens
Closes #146
=> fix: HTML overlay elements responsiveness (for leaderboard)

js/script.js
1. Removed the bug causing the speed to increase on press of the resume key.
Closes #153
=> Fix(Client): Speed reduced to normal

js/script.js
1. Updated window.onload function for title screen images
Loads the title screen background and the logo at the same time
Closes #151
=> fix: onload for title screen images

js/script.js
1. Updated onTimer function so timer so stopTime = 0
Closes #160
=> fix: timer countdown stops at 0

css/styles.css
1. Adjusted the top and right position of certain elements
Closes #163
=> Fix(Client)Improved responsiveness

js/script.js
1. Improved on the score feature and added the score of the eaten pies to  score of the scroll position.
2. Improved on  the timer bonus to multiply with the left time in the timer. 
Resolves the score problem. 
Closes #155
=> Fix: Added Score to ScrollPosition, timerbonus

js/script.js
1. Added Hurt function to call when hurt by obstacles
2. Cat moves away from obstacle over time
Cat/Player would teleport away from objects when hurt
Closes #102
=> Added hurt animation

js/leaderboard.js, js/script.js
1. Removed Commented code and extra Console logs
Make sure code is in cleaner state
=> Final push, cleaned up comments

js/script.js
1. updates score to final calculated score
=> added final score to score variable
